# Generated by Django 4.1.3 on 2022-11-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('career_average_points', models.IntegerField()),
            ],
        ),
    ]
