# Generated by Django 4.1.3 on 2022-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='career_average_points',
        ),
        migrations.AddField(
            model_name='player',
            name='career_average_ppg',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=3),
            preserve_default=False,
        ),
    ]
