# Generated by Django 4.1.3 on 2022-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_player_career_average_ppg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='career_average_ppg',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
