# Generated by Django 4.1.3 on 2022-11-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pastgames'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastGames',
            new_name='PastGame',
        ),
    ]
