# Generated by Django 4.1.3 on 2022-11-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_pastgames_pastgame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastgame',
            options={'ordering': ['-date']},
        ),
    ]
