# Generated by Django 4.1.3 on 2022-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='main_app.skill'),
        ),
    ]
